@startuml

class Cliente {
  - nome: string
  - cpf: int
  - email: string
  - senha: string
}

class Lojista {
  - nome: string
  - cnpj: int
  - email: string
  - senha: string
}

class Cadastro {
  - id_usuario: string
  - nome_usuario: string
  - email: string
  - cpf: string
  - telefone: string
  - senha: string
  --
  + atualizarNome(...)
  + atualizarEmail(...)
}

class Espaco {
  - id_espaco: string
  - nome_espaco: string
  - capacidade: int
  - preco_diaria: double
  - fotos: List(string)
  --
  + verificarDisponibilidade(data): boolean
}

class Reserva {
  - id_reserva: string
  - id_cliente: string
  - id_espaco: string
  - data: Date
  - valor_total: double
  - status_reserva: string
  --
  + calcularValorTotal(): double
  + cancelar()
  + verificarStatusPagamento(): string
}

class Pagamento {
  - id_pagamento: int
  - valor_pago: double
  - data_pagamento: Date
  - status_pagamento: string
  --
  + confirmarPagamento()
}

class InterfaceAplicativo <<interface>> {
  + leEntradaUsuario(...)
  + leEntradaLojista(...)
}

class ControladorGeral {

}

class ServiçoEspaco {
  + cadastrarEspaco(...): Espaco
  + modificarDetalhesEspaco(...): Espaco
  + removerEspaco(id_espaco): boolean
  + verificarEspacosCadastrados(id_lojista): list<Espaco>
}

class ServiçoReserva {
  + criarReserva(...): Reserva
  + verificarReserva(id_reserva): Reserva
  + alterarReserva(...): Reserva
  + cancelarReserva(id_reserva): boolean
}

class ServiçoPagamento {
  + realizarPagamento(...): Pagamento
  + consultarStatusPagamento(id_reserva): string
}

class ServiçoCadastro {
  + cadastrarUsuario(...): Usuario
  + cadastrarLojista(...): Lojista
}



Cliente -down-> InterfaceAplicativo
Lojista -> InterfaceAplicativo

InterfaceAplicativo -right-> ControladorGeral
ControladorGeral -up-> ServiçoEspaco
ControladorGeral -right-> ServiçoReserva
ControladorGeral -down-> ServiçoPagamento
ControladorGeral --> ServiçoCadastro

ServiçoEspaco -> Espaco
ServiçoReserva -> Reserva
ServiçoPagamento -> Pagamento
ServiçoCadastro -left-> Cadastro

@enduml